#!/usr/bin/env node
/* Inline every asset into a single self-contained karaneh-system.html so the
 * user can double-click it and run the system with no server and no network.
 *   node tools/build.js
 */
'use strict';
var fs = require('fs');
var path = require('path');
var ROOT = path.join(__dirname, '..');

function read(p) { return fs.readFileSync(path.join(ROOT, p), 'utf8'); }

/* A </script> inside a string literal would close the wrapping tag; the split
   form is inert to the HTML parser and identical to JavaScript. */
function safe(js) { return js.replace(/<\/script>/gi, '<\\/script>'); }

var parts = {
  css:      read('src/styles.css'),
  sheetjs:  read('vendor/xlsx.full.min.js'),
  sample:   read('sample-data/sample-data.js'),
  engine:   read('src/calculation-engine.js'),
  store:    read('src/data-store.js'),
  importer: read('src/excel-import.js'),
  postproc: read('src/xlsx-postprocess.js'),
  ui:       read('src/ui.js'),
  app:      read('src/app.js')
};

var html = [
  '<!DOCTYPE html>',
  '<html lang="fa" dir="rtl">',
  '<head>',
  '<meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1">',
  '<title>سامانه مدیریت کارانه</title>',
  '<!--',
  '  KARANEH MANAGEMENT SYSTEM — single-file build',
  '  Generated by tools/build.js from the modules under src/.',
  '  Edit the sources, not this file, then re-run the build.',
  '',
  '  Bundled: SheetJS (xlsx) 0.18.5 — Apache-2.0 — https://sheetjs.com',
  '  Everything runs locally in the browser. No network calls are made.',
  '-->',
  '<style>',
  parts.css,
  '</style>',
  '</head>',
  '<body>',
  '<div id="app">',
  '  <div style="padding:40px;text-align:center;font-family:Tahoma,sans-serif">در حال بارگذاری…</div>',
  '</div>',
  '<noscript>',
  '  <div style="padding:40px;text-align:center;font-family:Tahoma,sans-serif">',
  '    برای استفاده از این سامانه، JavaScript باید در مرورگر فعال باشد.',
  '  </div>',
  '</noscript>',
  '<script>' + safe(parts.sheetjs)  + '</' + 'script>',
  '<script>' + safe(parts.sample)   + '</' + 'script>',
  '<script>' + safe(parts.engine)   + '</' + 'script>',
  '<script>' + safe(parts.store)    + '</' + 'script>',
  '<script>' + safe(parts.importer) + '</' + 'script>',
  '<script>' + safe(parts.postproc) + '</' + 'script>',
  '<script>' + safe(parts.ui)       + '</' + 'script>',
  '<script>' + safe(parts.app)      + '</' + 'script>',
  '</body>',
  '</html>',
  ''
].join('\n');

var out = path.join(ROOT, 'karaneh-system.html');
fs.writeFileSync(out, html, 'utf8');
console.log('built ' + path.relative(ROOT, out) + ' — ' +
            (Buffer.byteLength(html) / 1024).toFixed(0) + ' KB');
